version: "3.9"

networks:
  bit:
    external: false

services:
  app:
    build: .
    container_name: "bit_app"
    environment:
      SERVER_PORT: 3000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bit
      SPRING_DATASOURCE_USERNAME: bituser
      SPRING_DATASOURCE_PASSWORD: qwerty1234
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bit
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "bit_db"
    restart: always
    environment:
      - POSTGRES_USER=bituser
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_DB=bit
    networks:
      - bit
    volumes:
      - ./postgres:/var/lib/postgresql/data